### ISSUE TITLE
Arreglar links del Readme.md principal 

### ISSUE THREAD

**Issue by Garibaldy** [developersdo/learning#88]
algunos enlaces direccionan a 404 , especificamente los relacionados a 
- Front-end Frameworks
- SQL Databases
- NO-SQL Data Stores
- Arquitectura de Software

**Comment by Garibaldy** [comment]
Quienes estan encargados de hacer los merges en este repositorio ?
 Hay algun proceso que se deba seguir para hacer merge aqui ?

**Comment by EfrainReyes** [comment]
Ahora es que vi la notificación. Lo chequeo en un ratico.

**Comment by Garibaldy** [comment]
Bien :)
